package com.retexspa.xr.ms.main.graphql.queries;

public class NegozioGraphqlQueries extends BaseGraphqlQuery{

    public static String search(int page){
        return String.format(
          "{\"query\":\""
              + "query { "
              + "  negozioSearch(negozioSearchRequest: {"
              + "    page: %s,"
              + "    limit: %s"
              + "    sort: [{orderType: \\\"ASC\\\", orderBy: \\\"codice\\\"}]"
              + "  }) {"
              + "  records {"
              + "  id "
              + "  codice "
              + "  descrizione"
              + "  ragioneSociale"
              + "  codiceFiscale"
              + "  regimeFiscale"
              + "  magazzino"
              + "  differenzialePartitaIVA"
              + "  nazionePartitaIVA"
              + "  partitaIVA"
              + "  ivaVentilata"
              + "  reaUfficio"
              + "  reaNumero"
              + "  reaCapitaleSociale"
              + "  reaSocioUnico"
              + "  reaLiquidazione"
              + "  codiceDestinatarioSDI"
              + "  sedeLegaleIndirizzo"
              + "  sedeLegaleNumeroCivico"
              + "  sedeLegaleCAP"
              + "  sedeLegaleComune"
              + "  sedeLegaleProvincia"
              + "  sedeLegaleNazione"
              + "  sedeOperativaNome"
              + "  sedeOperativaIndirizzo"
              + "  sedeOperativaNumeroCivico"
              + "  sedeOperativaCAP"
              + "  sedeOperativaComune"
              + "  sedeOperativaProvincia"
              + "  sedeOperativaNazione"
              + "  telefono"
              + "  cellulare"
              + "  fax"
              + "  email"
              + "  pec"
              + "  web"
              + "  iban"
              + "  nazioneTrasmittente"
              + "  partitaIvaTrasmittente"
              + "  codiceAteco"
              + "  canale"
              + "  insegna"
              + "  nome"
              + "  gerarchia {"
              + "  id"
              + "    }"
              + "    }"
              + "  }"
              + "}\"}",
          page, MAX_LIMIT);
    }

    public static String count(){
        return String.format(
            "{\"query\":\""
                + "query { "
                + "  negozioSearch(negozioSearchRequest: {"
                + "    page: 0,"
                + "    limit: 10"
                + "  }) {"
                + "    pagination {"
                + "      count"
                + "    }"
                + "  }"
                + "}\"}");
    }

    public static String negozioById(String aggregatoId){
            return String.format(
                "{\"query\":\""
                                + "query { "
                                + "  negozioById(id: \\\"%s\\\"){"
                                + "  codice "
                                + "  descrizione"
                                + "  ragioneSociale"
                                + "  codiceFiscale"
                                + "  regimeFiscale"
                                + "  magazzino"
                                + "  differenzialePartitaIVA"
                                + "  nazionePartitaIVA"
                                + "  partitaIVA"
                                + "  ivaVentilata"
                                + "  reaUfficio"
                                + "  reaNumero"
                                + "  reaCapitaleSociale"
                                + "  reaSocioUnico"
                                + "  reaLiquidazione"
                                + "  codiceDestinatarioSDI"
                                + "  sedeLegaleIndirizzo"
                                + "  sedeLegaleNumeroCivico"
                                + "  sedeLegaleCAP"
                                + "  sedeLegaleComune"
                                + "  sedeLegaleProvincia"
                                + "  sedeLegaleNazione"
                                + "  sedeOperativaNome"
                                + "  sedeOperativaIndirizzo"
                                + "  sedeOperativaNumeroCivico"
                                + "  sedeOperativaCAP"
                                + "  sedeOperativaComune"
                                + "  sedeOperativaProvincia"
                                + "  sedeOperativaNazione"
                                + "  telefono"
                                + "  cellulare"
                                + "  fax"
                                + "  email"
                                + "  pec"
                                + "  web"
                                + "  iban"
                                + "  nazioneTrasmittente"
                                + "  partitaIvaTrasmittente"
                                + "  codiceAteco"
                                + "  canale"
                                + "  insegna"
                                + "  nome"
                                + "  gerarchia {"
                                + "  id"
                                + "  }"
                                + "  }"
                                + "  }"
                                + "\"}",
                aggregatoId);
    }
    
}
