name: mvn-deploy
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v4   
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'                
      - name: Publish package
        env:
          GH_USER: ${{ secrets.XR_GITHUB_USER }}    
          GH_TOKEN: ${{ secrets.XR_GITHUB_TOKEN }}      
        run: mvn  -s .mvn/settings.xml --batch-mode deploy